apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-flask.fullname" . }}
  labels:
    {{- include "chart-flask.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart-flask.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart-flask.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "demoyuw/flask-api:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 10009
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
